#ifndef GAME_CONSTANTS_H_INCLUDED
#define GAME_CONSTANTS_H_INCLUDED

#define RASTER_WIDTH (1080)
#define RASTER_HEIGHT (1080)

/// BACKGROUND STARS

#define CLOSEST_STAR_SIZE 5
#define MIDDLE_STAR_SIZE 3
#define FARTHEST_STAR_SIZE 1

#define CLOSEST_STAR_SPEED 1
#define MIDDLE_STAR_SPEED 0.4
#define FARTHEST_STAR_SPEED 0.06

#define CLOSEST_STAR_COUNT 100
#define MIDDLE_STAR_COUNT 200
#define FARTHEST_STAR_COUNT 300

#define MAX_SMOKE_PARTICLES 250


#endif // GAME_CONSTANTS_H_INCLUDED
